name: CICD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]
    
jobs:
 mulelint:
  uses: teksystemsind/reusable-workflows/.github/workflows/run-mule-lint.yml@master
 test:
  needs: mulelint
  uses: teksystemsind/reusable-workflows/.github/workflows/run-munits.yml@master
  
 build:
  needs: test
  uses: teksystemsind/reusable-workflows/.github/workflows/build-mule.yml@master
        
 deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8    
    - name: Deploy to Sandbox
      env:
        USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
        PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy -DskipTests -DmuleDeploy \
         -Dmule.artifact=$artifactName \
         -Danypoint.username="$USERNAME" \
         -Danypoint.password="$PASSWORD"
