name: CICD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]
    
jobs:
 mulelint:
  uses: teksystemsind/reusable-workflows/.github/workflows/run-mule-lint.yml@master
 test:
  needs: mulelint
  uses: teksystemsind/reusable-workflows/.github/workflows/run-munits.yml@master
  
 build:
  needs: test
  uses: teksystemsind/reusable-workflows/.github/workflows/build-mule.yml@master
        
 deploy:
    needs: build
    uses: teksystemsind/mule-cicd/.github/workflows/deploy.yml@master
    with:
      artifactName: $(ls *.jar | head -1)
    secrets:
      ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
      ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
