name: deploy
on:
 workflow_call:
  inputs:
   artifactName:
    description: Artifact Name of the Artifact to be deployed
    type: string
    required: true
  secrets:
   ANYPOINT_USERNAME:
    required: true
   ANYPOINT_PASSWORD:
    requiredL: true

jobs:
 Deploy to Sandbox:
  runs-on: ubuntu-latest
  run: mvn deploy -DskipTests -DmuleDeploy -Dmule.artifact=$artifactName -Danypoint.username="$ANYPOINT_USERNAME" -Danypoint.password="$ANYPOINT_PASSWORD"  
