name: deploy
on:
 workflow_call:
  inputs:
   artifactName:
    description: Artifact Name of the Artifact to be deployed
    type: string
    required: true
  secrets:
   ANYPOINT_USERNAME:
    required: true
   ANYPOINT_PASSWORD:
    required: true

jobs:
 deploy-to-cloudhub:
  runs-on: ubuntu-latest
  steps:
   - name: Deploy to Cloudhub
     run: mvn deploy -DskipTests -DmuleDeploy -Dmule.artifact=$artifactName -Danypoint.username="$ANYPOINT_USERNAME" -Danypoint.password="$ANYPOINT_PASSWORD"  
